### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by taniakolesnik**
The Met website learning project.
css, html, no JS

Preview link wont work because of style file path in index html.

instructions on how to preview file locally:

clone project to your pc

run "npm i" within project folder

switch to develop branch

run "npm start" within project folder

check site on http://localhost:1234/

[preview link] (https://taniakolesnik.github.io/layout_landing-page/)

[figma project](https://www.figma.com/file/lSR1m42L9YwzQwzzxKwHpw/THE-MET)

PS: god/gods help you checking this ugly code

### CODE REVIEW

**Comment by taniakolesnik** [comment]
Please do not check yet. it's not ready for checks. submitted not to loose streak. sorry.

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
Problem with styles in demo link should be solved.

With such problem earlier helped increasing versions of such dependencies:
`npm i parcel@1.12.3 -D`
`npm i @mate-academy/scripts@1.2.8 -D`

**Comment by taniakolesnik** [comment]
дякую. бачу шо превью чомусь не показує всі зміни
https://mate.academy/chats/20607?selectedMessageId=4265196 запитала в чаті

**Comment by taniakolesnik** [comment]
vse ok preview now. please rfeel free to review.

**Review by etojeDenys — CHANGES_REQUESTED** [review]
1. looks different from the mockup
image

2. 
image
image

3. 
image
image

4. it should be links with some hover
image


5. number should appear on hover
image


6. disable scrolling if the menu is open
image


7. feel free to ask for some help in the chat

**Pull request closed without merging**
