### PR TITLE
add project

### PR DESCRIPTION
**Pull request by dimarogkov**
[DEMO LINK](https://dimarogkov.github.io/layout_landing-page/)

### CODE REVIEW

**Review by IvanFesenko — COMMENTED** [review]
Pay attention, your demo link isnt working. Use this correct one 
https://dimarogkov.github.io/layout_landing-page/

**Review by IvanFesenko — CHANGES_REQUESTED** [review]
menu isn't working
https://github.com/mate-academy/layout_landing-page/assets/61904995/77c56a0b-3a8a-43ff-99a0-107e0a2fd5df

**Review by mykhalenych — CHANGES_REQUESTED** [review]
Screenshot 2023-05-25 at 17 08 59
your menu isn't working, add correct href, and close menu after click

**Review by anstsot — APPROVED** [review]
Great job, approved!

**Pull request closed without merging**
