### PR TITLE
pull request for Oleh Bazyla

### PR DESCRIPTION
**Pull request by pakhomovalex**
It`s not finished project, this pull request was created for description problem for Oleh Bazyla
[DEMO LINK](https://pakhomovalex.github.io/layout_landing-page/)
[MYBIKE landing](https://www.figma.com/file/NZQAIydtHo5QkINyGLHNcq/BIKE-New-Version?node-id=0%3A1)

### CODE REVIEW

**Comment by pakhomovalex** [comment]
if open menu on a Desktop, then on a mobile or a tablet will show up overflow-x, I have no idea how I can fix it

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
Apply `cursor: pointer` for all interactable elements 
image

**Review by maxim2310 — CHANGES_REQUESTED** [review]
Good work, but lets make some improvement 

1. remove autofill styles 
image
2. would be nice to add hover 
image
3. check img position on tablet
image
image

**Comment by pakhomovalex** [comment]
> Good work, but lets make some improvement
> 
> 1. remove autofill styles
>    image
> 2. would be nice to add hover
>    image
> 3. check img position on tablet
>    image
>    image

in the mockup on tablet header section size is 744x628, in that size I have a normal picture

**Review by etojeDenys — APPROVED** [review]
lgtm

**Pull request closed without merging**
