### PR TITLE
New Develop Met

### PR DESCRIPTION
**Pull request by vovan4ik1**
[DEMO LINK](https://vovan4ik1.github.io/layout_landing-page/)

### CODE REVIEW

**Comment by vovan4ik1** [comment]
I have Bag 
image

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great start! Consider fixing the logo: feel free to ask for help in the chat 
Screenshot 2024-08-15 at 17 36 17
Screenshot 2024-08-15 at 17 36 29
Check the styles for the icon in the Figma
Screenshot 2024-08-15 at 17 37 49
Consider using a link to Google Maps

**Comment by vovan4ik1** [comment]
> [DEMO LINK](https://vovan4ik1.github.io/layout_landing-page/)

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
1. logo in menu is not displayed 
image
2. should be links to google maps
image

**Comment by TarasHoliuk** [comment]
See [the checklist](https://github.com/mate-academy/layout_landing-page/blob/main/checklist.md) point 6.

Related to the google.maps links

**Review by TarasHoliuk — CHANGES_REQUESTED** [review]
Great job!

One more small fix is required (it's from the checklist)

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Make sure to deploy your solution

**Comment by vovan4ik1** [comment]
I add new commit

**Review by anastasiiavorobiova — APPROVED** [review]
Awesome work!

**Comment by vovan4ik1** [comment]
Thank you , mentors for your advice!

**Pull request closed without merging**
