### PR TITLE
add a header block

### PR DESCRIPTION
**Pull request by yuurex**
- Deploy and create a Pull Request with a [DEMO LINK](https://yuurex.github.io/layout_landing-page/)

На цьому моменті я зробив Header частину, вирішив задеплоїти, щоб дізнатись про свої помилки на цьому етапі, якщо вони є)
Також бачу, що розмір картинок дуже великий, може це треба буде виправити?

### CODE REVIEW

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work! Keep doing!

**Comment by yuurex** [comment]
at this stage I have created a side menu, I want to know my mistakes if there are any)

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
The deploy looks a bit broken. Try to redeploy your page

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
mobile looks good. keep working to complete task. Re-request review when you finish whole landing. 

1. add favicon
2. add more meaningful page title

**Review by etojeDenys — CHANGES_REQUESTED** [review]
Great! If you've already reached the lesson on the landing page, go ahead and continue working on that task to make everything look like in Figma. If not, just keep studying, and you can finish this task later

**Review by etojeDenys — CHANGES_REQUESTED** [review]
1. it looks different
image
image


2. disable scroll if the menu is open
3. add hover to all links and card's photo
4. it should be the links
image

5. should be the button
image

6. don't forget to follow this file https://github.com/yuurex/layout_landing-page/blob/develop/checklist.md

7. looks like you need to center those cards
image

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work!
- Screenshot 2024-10-25 at 16 30 16
- Check the background position for tablets
- Screenshot 2024-10-25 at 16 30 06
- The menu should be scrollable in the landscape mode
- Screenshot 2024-10-25 at 16 29 39
- The click on the submit button should clear form fields
- All fields should be required
- Screenshot 2024-10-25 at 16 29 26
- Check fonts here
- Screenshot 2024-10-25 at 16 29 06
- Consider using a `mailto` link, `tel` link and the link to Google Maps here
- Screenshot 2024-10-25 at 16 28 45
- Consider exporting an image without a label
- Screenshot 2024-10-25 at 16 28 33
- Screenshot 2024-10-25 at 16 28 38
- Consider adding hover styles here (showing the phone number, changing an image, etc.)

**Pull request closed without merging**
