### PR TITLE
add task solution

### PR DESCRIPTION
**Pull request by VladyslavKolisnyk**
DEMO LINK https://vladyslavkolisnyk.github.io/layout_landing-page/

### CODE REVIEW

**Review by Volodymyr-Melnyk-Fron10der — CHANGES_REQUESTED** [review]
Check it on the design. If you have any questions - ask them in the Slack plz 
image

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
I think it will be better if you add margin-left for text in input
image

**Comment by TarasHoliuk** [comment]
In mobile and tablet view there are no margins between form fields:

image

Should be fixed

**Review by TarasHoliuk — CHANGES_REQUESTED** [review]
Well done! Almost perfect except for 1 thing (check comments)

**Review by vlad-demchuk — CHANGES_REQUESTED** [review]
not fixed

image

**Review by vlad-demchuk — APPROVED** [review]

**Pull request closed without merging**
