### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Prokopovych16**
- Deploy and create a Pull Request with a [DEMO LINK](https://Prokopovych16.github.io/layout_landing-page/)

### CODE REVIEW

**Review by nazarmatsevych — CHANGES_REQUESTED** [review]
Hi, good start!

Please, re-request review when the entire task will be done (check yourself using the CHECKLIST when finished)

If you have any questions feel free to ask in the chat

**Review by denys-danyliuk — CHANGES_REQUESTED** [review]
Keep going!
Re-request review after you'll finish whole landing

**Comment by Prokopovych16** [comment]
If I am not mistaken, I have coped with all points of the task.
Could you tell me what's wrong pls?

**Review by denys-danyliuk — CHANGES_REQUESTED** [review]
your demo page now look like this, you connect in your html file which doesn't exist
Знімок екрана 2023-12-12 о 13 36 36
Знімок екрана 2023-12-12 о 13 37 58

**Pull request closed without merging**
