### PR TITLE
add header + menu for mobile

### PR DESCRIPTION
**Pull request by valeriaoleynik**
[DEMO LINK](https://valeriaoleynik.github.io/layout_landing-page/)

### CODE REVIEW

**Review by polosanya — CHANGES_REQUESTED** [review]
Nice start!
1. Background image doesn't match the design.
image
Also, check indentations according to the design
image
2. Phone number should be shown on hover
image
image
3. Links should have underline on hover
image
image

**Review by lerastarynets — CHANGES_REQUESTED** [review]
Pls watch the video review :)

https://github.com/mate-academy/layout_landing-page/assets/77551820/75b6f17f-e2ce-4a29-836d-95ab51b0ef72

**Review by sTorba24 — CHANGES_REQUESTED** [review]
Good start! Keep it up

Rerequest review when you finish the whole page

**Review by lerastarynets — CHANGES_REQUESTED** [review]
Pls watch the video review :)

https://github.com/mate-academy/layout_landing-page/assets/77551820/dc397efa-7b12-49f8-be62-89458e5ff407

**Pull request closed without merging**
