### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by no4kar**
https://no4kar.github.io/layout_landing-page/

### CODE REVIEW

**Review by loralevitska — CHANGES_REQUESTED** [review]
hi) 
regarding your question I tested this block in the desktop mode and now everything is fine there. If you have any questions, please ask them in fe_chat and tag mentors. It will be faster, because your answers in GitHub will be visible to mentor only after you re-request review
Also let's try to improve your landing:
- add phone number by phone icon hover
image
- make sure that all interactive elements have a cursor pointer on hover
- fix image overlap 
image
- add smooth page scrolling 
- remove default autocomplete background color in fields, it breaks design 
image
- make required all form fields

**Review by Andriy-Shymkiv — CHANGES_REQUESTED** [review]
- add transition:
image
- also here:
image

great job at all, but most of your images have a really bad quality. is it the ones you imported from figma with such quality or what? can you fix it somehow?

**Review by Viktor-Kost — CHANGES_REQUESTED** [review]
Nice work!

### To improve: 
1) add correct href to a phone number at header (the same as you've added at footer)
2) As previous mentor asked - remove default autocomplete styles
Screenshot 2023-08-21 at 13 59 19

3) add a favicon to your page
4) remove page scrolling when mobile menu is opened

**Review by OleziO — CHANGES_REQUESTED** [review]
image

Make it phone link

**Review by OleziO — APPROVED** [review]

**Pull request closed without merging**
