### PR TITLE
solution

### PR DESCRIPTION
**Pull request by Oleh-Rybachuk**

### CODE REVIEW

**Review by mykhalenych — CHANGES_REQUESTED** [review]
where is your demo link?

**Comment by Oleh-Rybachuk** [comment]
https://oleh-rybachuk.github.io/layout_landing-page/

**Review by etojeDenys — CHANGES_REQUESTED** [review]
good start

keep going

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
A few comments for header:
- what is red line in header?
Screenshot from 2023-08-02 13-35-23
- prevent scroll page when menu is opened
- on hover to phone icon should appear phone number tooltip ( check design).
Screenshot from 2023-08-02 13-37-34

Waiting other sections.

**Pull request closed without merging**
