### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by VladChudin**
[DEMO LINK](https://VladChudin.github.io/layout_landing-page/)

### CODE REVIEW

**Comment by TarasHoliuk** [comment]
1. Read the [checklist ](https://github.com/mate-academy/layout_landing-page/blob/main/checklist.md) and make sure you reached all points.

2. You set the page title but it doesn't match with the page content. It should be `Bang & Olufsen` instead of Miami.

3. Hover effect on the phone icon hover:
image

4. Import images in better quality from Figma (import from the desktop version mockup):
image
image

5. It should be links (address link is external - do not miss the point in the checklist about that):
image

6. The border (or outline) in the mobile version looks good - it's orange:
image

Unlike in desktop version - blue:
image

**Review by TarasHoliuk — CHANGES_REQUESTED** [review]
Looks great! But there are a few things that should be fixed/improved

**Review by GUSILLUS — COMMENTED** [review]
GJ!

1. Consider adding max-width property to your content similar to design
2. Consider fixing hover overlapping

**Review by GUSILLUS — CHANGES_REQUESTED** [review]
Good try

**Comment by VladChudin** [comment]
I considered adding a max-width for design, on my opinion better when design adapts to any screen size, in conditions where it was not said to make a width limitation, so I think everything is fine with me, and regarding the 2nd comment, I don't understand it

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Good job 👍 
Let's improve your page
1. Change the autofill styles for the form fields
https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/ 
image

2. Add a favicon the page 
image

3. Fix font weight for the prices, check it on the layout 
image

4. Need to reset form fields after submitting the form 
image

5. Make all these fields are required before sending 
image

6. Add cursor pointer and remove default border for the button 
image

7. Open this additional link in the new tab 
image

8. Hide the additional phone number on the mobile and tablet version and make a call when user is clicking on this icon 
image

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work! 
Screenshot 2024-09-03 at 22 39 35
A user should be able to scroll the menu 
Screenshot 2024-09-03 at 22 38 22
Consider using tel and mailto links here 
Screenshot 2024-09-03 at 22 37 54
A user should be able to call by clicking here

**Comment by VladChudin** [comment]
> Great work! Screenshot 2024-09-03 at 22 39 35 A user should be able to scroll the menu Screenshot 2024-09-03 at 22 38 22 Consider using tel and mailto links here Screenshot 2024-09-03 at 22 37 54 A user should be able to call by clicking here

I think users don't need this thigs on a PC, because you can call only with your phone, i checking this on my phone and it working.

**Pull request closed without merging**
