### PR TITLE
add task solution

### PR DESCRIPTION
**Pull request by MishaTumak**
[DEMO LINK](https://MishaTumak.github.io/layout_landing-page/)

### CODE REVIEW

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work! 
Screenshot 2023-11-14 at 16 08 55
Consider fixing validation errors 
Screenshot 2023-11-14 at 16 07 29
Check the size of the button for tablets 
Screenshot 2023-11-14 at 16 06 55
A user should be able to scroll the menu in landscape mode 
Screenshot 2023-11-14 at 16 06 26
Check margins between elements 
Screenshot 2023-11-14 at 16 06 07
Check margins between elements  and make sure the placeholder is visible 
Screenshot 2023-11-14 at 16 06 34
Screenshot 2023-11-14 at 16 06 39
Screenshot 2023-11-14 at 16 07 14
Check an alignment of your elements

**Comment by MishaTumak** [comment]
show me exactly what the problem is, I can't run the test, after the crash of the PC
image

**Review by sTorba24 — CHANGES_REQUESTED** [review]
So run 
rm -rf node_modules package-lock.json
npm i
npm start

and use please your fe_chat if you have any issues, there will be easier to help
because on github we can see your comments only after request review and it's hard to communicate in such way

**Comment by MishaTumak** [comment]
image
I tried to fix the errors you mentioned, but I couldn't fix the npm error, everything works fine in other tests. you can accept the task and I will go to do other tests where npm works.

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
try to run `npm run deploy -- -l`
it should show more information about problems with deploy.
And, please, if you have any issuew - please ask in fe_chat. It will be faster and more effective communication.
Make next re-request after solve issue with deploy.

**Pull request closed without merging**
