### PR TITLE
add task solution

### PR DESCRIPTION
**Pull request by vbevziuk**
[DEMO LINK](https://vbevziuk.github.io/layout_landing-page/)

### CODE REVIEW

**Review by Viktor-Kost — CHANGES_REQUESTED** [review]
Nice work!

### To improve: 
1. Display phone number when you hover at phone icon
Screenshot 2023-09-07 at 19 03 11

2. Favicon isn't readable. Either use cut variant of logo or don't stretch the picture


3. Add a transition to button and link hover effects
4. Set correct font styles
Screenshot 2023-09-07 at 19 07 15

**Review by Viktor-Kost — CHANGES_REQUESTED** [review]
Great!

Check my previous comment:
_**Set correct font styles**_

The form message placeholder doesn't fit the design

**Comment by vbevziuk** [comment]
> Great!
> 
> Check my previous comment: _**Set correct font styles**_
> 
> The form message input styles doesn't fit the design

sorry, I checked in Safari and everything was ok, now I see that it is not displayed in Chrome as it should be.
Solved, please check!

**Review by etojeDenys — APPROVED** [review]
lgtm

**Pull request closed without merging**
