### PR TITLE
MyBike

### PR DESCRIPTION
**Pull request by genakorytov**
https://genakorytov.github.io/layout_landing-page/

### CODE REVIEW

**Review by etojeDenys — CHANGES_REQUESTED** [review]
probably, you forgot to deploy your hw, cause link does not work

**Review by Viktor-Kost — CHANGES_REQUESTED** [review]
Hello!

### To improve: 
1) fix z-index
Screenshot 2023-06-20 at 23 17 32

2) use svg for all icons
3) remove body scroll when menu is opened
4) add a favicon
5) check sizes
Screenshot 2023-06-20 at 23 20 38

6) check markup (radius and fonts)
Screenshot 2023-06-20 at 23 21 19

**Review by etojeDenys — CHANGES_REQUESTED** [review]
let's disable resizing

https://github.com/mate-academy/layout_landing-page/assets/70220667/e7d25af0-8925-495c-8da2-35a85d83b3ec
2. i should see a number on hover
image

**Review by Viktor-Kost — CHANGES_REQUESTED** [review]
Hello!)
Cool!

### To improve:
1) form should match the figma design
remove input/button borders
Screenshot 2023-06-26 at 22 52 25

set correct border-radius
Screenshot 2023-06-26 at 22 54 39

2) phone icon shouldn't hide on hover
Screenshot 2023-06-26 at 22 55 33

3) Use different images for different screen sizes (mobile, tablet, desktop) using media-queries. You can download these images from figma. We don't want to use big image file size from desktop at mobile screen. It's ruining your website experience. [Here](https://www.theessential.agency/blog/are-images-ruining-your-website-experience) you can find why is it important

4) decrease padding-top to fit the design
Screenshot 2023-06-26 at 23 00 05

5) add transition-duration to make your hover effects smooth (250-300ms would be nice)

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
Good job.
Needs some improvements.
-  mismatch with design:
actual:
Screenshot from 2023-06-29 13-26-08
design:
Screenshot from 2023-06-29 13-25-58
- add `resize: none` for textarea styles
chrome-capture-2023-5-29 (1)
- add trainsition property for elements with hover effect on screencast. also check other elements with hover effect.
hover-29
-  fis type on title `MyBike`
Screenshot from 2023-06-29 13-17-15

**Pull request closed without merging**
