### PR TITLE
the-met-landing 1-st commit

### PR DESCRIPTION
**Pull request by RSydorenko322**
DESCRIPTION

This is a site's landing page presenting elements of museum exhibits. Here we have 4 main blocks and each of them has its own function. We have a big enchanting main photo, pull-right menu, combination of information considered useful to a user such as adresses with links to the real places to visit and phone numbers.

TECHNIQUES

HTML/CSS/ Active using mixins and scss variables/ Typical techniques as pseudo-selectors/classes, transforming text and blocks with a definitive transition time and etc.

LINKS

[DEMO LINK](https://RSydorenko322.github.io/layout_landing-page/)
[MET landing](https://www.figma.com/file/lSR1m42L9YwzQwzzxKwHpw/THE-MET)

ADDITIONAL INSTRUCTIONS FOR LAUNCHING

It`s recommended to prepare up-to-date browser for working with a landing data. This folder is being a seperate html/scss product consisting of devided files for styles/mixins/variables. User managing that documents has to have all the instruments to work with scss extension.

### CODE REVIEW

**Review by etojeDenys — CHANGES_REQUESTED** [review]
1. looks different from the mockup
image

2. it's must be the textarea
image

3. make all inputs required
4. center your content
image
you can just add to that class `margin: 0 auto;`
image

5. the number must appear on hover
image

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
Almost done. 
Still needs some improvements.
- header content not centered horizontally
Screenshot from 2024-01-12 18-18-07
Screenshot from 2024-01-12 18-17-45
- phone tooltip doesn't match to design. every phone number should be a link to start call (pnone icon shouldn't be a link in this case)
actual:
Screenshot from 2024-01-12 18-20-00

design
Screenshot from 2024-01-12 18-20-17

- add `resize: none` for textarea
chrome-capture-2024-1-12-qwe

- fix addresses links color.
Screenshot from 2024-01-12 18-17-15

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work! 
Screenshot 2024-01-14 at 16 10 11
Consider fixing the autocomplete background change here 
Screenshot 2024-01-14 at 16 10 01
Check styles for the form fields with Figma 
Screenshot 2024-01-14 at 16 09 33
Consider adding hover styles for links here

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work! Form styles should match with Figma 
Screenshot 2024-01-14 at 17 40 26
Screenshot 2024-01-14 at 17 40 35

**Review by Viktor-Kost — CHANGES_REQUESTED** [review]
### Nice!

### To improve:
1. add padding for this textarea similar you did with inputs above
Screenshot 2024-01-14 at 18 53 15

2. use svg for all icons and logo instead of png
3. add cursor pointer to an icon
4. add hover effect to a form button
5. remove inputs autocomplete background as previous mentor asked
Screenshot 2024-01-14 at 18 59 20

6. move a little bit higher to fit a mockup
Screenshot 2024-01-14 at 19 01 36



### Recommendations:
1. add max-width to section containers at desktop to avoid scaling infinitely (but background image should be still full page size)
Screenshot 2024-01-14 at 18 56 24

**Review by volodymyr-soltys97 — APPROVED** [review]
Great work 🔥

**Pull request closed without merging**
