### PR TITLE
land

### PR DESCRIPTION
**Pull request by AlexLiashenko19**

### CODE REVIEW

**Comment by TarasHoliuk** [comment]
1. [The checklist](https://github.com/mate-academy/layout_landing-page/blob/main/checklist.md) points: 1, 5, 6 7, 11, 12, 15

2. Check the size of icons and logo in the header (it should be bigger) on the desktop version. Use SVG for logo and icons for better quality (you can export it from figma as SVG)

3. Check the layout in Contact us section:

image

4. Check styles for inputs in the figma

5. Disable resize for the textarea

6. Each element should be a link (phone link, email link, to google map)

**Review by TarasHoliuk — CHANGES_REQUESTED** [review]
.

**Review by TarasHoliuk — CHANGES_REQUESTED** [review]
.

**Review by TarasHoliuk — CHANGES_REQUESTED** [review]
.

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Good job!
To improve:
1. Add a favicon on the page 
image

2. Add hover effects for all clickable elements and images on the page 
image

3. Need to show additional phone number when hovering this icon and make a call when user clicks here
image

4. Add transition when the menu appears on the page and remove scroll when menu is open 
image

5. Fix height for the textarea 
image

6. The user cannot be able to change size of the textarea 
image

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
.

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
.

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
.

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
.

**Review by etojeDenys — CHANGES_REQUESTED** [review]
1. add the favicon
image


2. number should appear on hover
image


3. disable the scroll if menu is open
4. margins are too big here
image

5. disable textarea resizing
image

6. it should be the links with some hover
image

7. don't forget to follow this file
https://github.com/AlexLiashenko19/layout_landing-page/blob/develop/checklist.md

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
Good job.
Needs some improvements.
Please, pay attention on [checklist](https://github.com/mate-academy/layout_landing-page/blob/main/checklist.md)
- Use the logo as a favicon
- Change text color on hover for phone, email, and address
- Make sure phone icons and phone numbers are real links to start a call
- All addresses should be links to some location on Google Maps. Open them in a new tab with target="_blank".
- Increase all images on hover (make them links to #, if there is no better option)
- All form fields should be required
- The page shouldn't be reloaded on form submit, but the fields should be cleared.
- Disable page scrolling under the menu
check other points from checklist...

Also:
- prevent resize textarea
Screenshot 2024-12-05 at 14 28 56
- show phone number on hover to phone icon in header (check design)

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Hi, the comments from the previous review still not fixed, you need to fix all comments and make deploy again after your changes

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Good job!
To improve:
1. The images shouldn't overlap each other when hovering 
image

2. Blocks should decrease as smoothly as they increase.
image

3. Fix this section, check it on the design 
image

4. Fix default color for this button 
image

5. Make all these fields are required before sending 
image

6. Need to make a call when user clicks on this icon 
image

7. Add transition when this menu appears on the page and remove scroll when menu is open 
image

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work!
- Screenshot 2024-12-15 at 15 05 57
- Check font weights in the form
- Form fields shouldn't jump on the hover
- The submit button click should clear the form

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
.

**Review by etojeDenys — CHANGES_REQUESTED** [review]
image
don't forget to fix it

**Review by etojeDenys — APPROVED** [review]

**Pull request closed without merging**
