### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by DariaSlayer**
[DEMO LINK](https://DariaSlayer.github.io/layout_landing-page/)

### CODE REVIEW

**Review by Esceype — CHANGES_REQUESTED** [review]
Wow !!! Great job !!! Let`s make some fixes based on design and UI logic.
Image that is on hover effect should not overlap other images:
image
Try to stretch this picture
image
Check the design for this picture:
image

**Comment by DariaSlayer** [comment]
your wow and exclamation marks got me blushing. thanks. gonna work on mistakes

**Review by Esceype — APPROVED** [review]
Flash!!! (as fast you fix the issues)  Perfect !!!

**Comment by DariaSlayer** [comment]
thank you a lot! this means a world to me

**Pull request closed without merging**
