### PR TITLE
add task solution

### PR DESCRIPTION
**Pull request by Q1W2E3R4T5Y6U7I8a**
[DEMO LINK](https://Q1W2E3R4T5Y6U7I8a.github.io/layout_landing-page/)

### CODE REVIEW

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
demo link is not working

**Comment by Q1W2E3R4T5Y6U7I8a** [comment]
> demo link is not working

but, how i can resolve this bug? if I can't see npm start.

image

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
This problem requires more detailed help from a mentor, please write to fe_chat

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Hi, the demo link still not working, feel free in the fe_chat for the help 
image

**Comment by Q1W2E3R4T5Y6U7I8a** [comment]
[DEMO LINK](https://Q1W2E3R4T5Y6U7I8a.github.io/layout_landing-page/)

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
Good job.

Needs some improvements
- Change text color on hover for phone, email, and address
- Increase all images on hover (make them links to #, if there is no better option)
- remove default border from inputs and button in form

Check other points in [checklist](https://github.com/mate-academy/layout_landing-page/blob/main/checklist.md)

**Comment by Q1W2E3R4T5Y6U7I8a** [comment]
Changed what u said except: remove default border from inputs and button in form.

Can't find that request in checklist, what i have now on page looks identical as on Figma, so... I am not sure to what change if i sd?

**Comment by TarasHoliuk** [comment]
> Changed what u said except: remove default border from inputs and button in form.
> 
> Can't find that request in checklist, what i have now on page looks identical as on Figma, so... I am not sure to what change if i sd?

1. It's not something critical, and it's ok to make sure requested changes are really needed and ask why it's required) The mentor's review is also about suggestions on how to make it better 🙂 (you will also add it to your portfolio).  Talking about comparing with the Figma mockup I'd say we can see the difference anyway:

App - there is a border:
image

Figma - no border:
image

2. The [checklist](https://github.com/mate-academy/layout_landing-page/blob/main/checklist.md) point 13.

3. Try to scale on a smaller number - when one image overlaps another it looks not very good:
image

4. General rule for transition - it should work in both ways. Do not add it to `element:hover` selector, add it to `element` selector:
image

P.S. There is `.detail__img:hover:hover` with two `:hover`. Should be just one

**Review by TarasHoliuk — CHANGES_REQUESTED** [review]
Hey! App looks nice 👍 

Answered your question. One of checklist points is not reached. Also, added a few more small comments

**Comment by Q1W2E3R4T5Y6U7I8a** [comment]
Ty!)

1. Done
2. Done
3. Done
4. Done

**Comment by Q1W2E3R4T5Y6U7I8a** [comment]
.

**Comment by Q1W2E3R4T5Y6U7I8a** [comment]
How to reopen PR? I pressed that button but didnt seem to work
image

**Pull request closed without merging**
