### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by SerhiiUnhurian**
[DEMO LINK](https://SerhiiUnhurian.github.io/layout_landing-page/)

### CODE REVIEW

**Review by denys-danyliuk — CHANGES_REQUESTED** [review]
Good start!
Send it on a review when it will be finished

**Review by denys-danyliuk — CHANGES_REQUESTED** [review]
it's not finished yet

**Review by xiimiik — CHANGES_REQUESTED** [review]
As the previous mentor wrote, please send the work for review only after it is fully completed

**Comment by SerhiiUnhurian** [comment]
там мені сказали закомітити щоб подивитись в чому пробема з фото, стандатрне фото не ставиться, одразу широке

**Review by Andriy-Shymkiv — CHANGES_REQUESTED** [review]
regarding grid you need to:
1. add `grid-column: 1 / span 5;` to contact__form
2. add `grid-column: 7 / span 3;` to contact__information
after that it will work properly, so please, finish your work (ask questions in chat if needed) and then request a review 😉

**Review by loralevitska — CHANGES_REQUESTED** [review]
Keep up the good work! Some comments to fix:
- implement this phone number by hover on phone icon
image
- don't reload page on form submit (15-th point from [checklist](https://github.com/mate-academy/layout_landing-page/blob/main/checklist.md))
- make all form fields required 
- these parts should be links and add hover effect 
image
- disable text-area resize, it breaks design 
image

**Review by mykhalenych — APPROVED** [review]

**Pull request closed without merging**
