### PR TITLE
Landing Page

### PR DESCRIPTION
**Pull request by vadymboichenkoAcupower**
[DEMO LINK](https://vadymboichenkoAcupower.github.io/layout_landing-page/)

### CODE REVIEW

**Comment by vadymboichenkoAcupower** [comment]
I was not going throught checklist yet. It was just to show current result for mentor

**Review by SerhiiKirik — CHANGES_REQUESTED** [review]
Well done 🔥 
Let's improve your solution 🧑‍💻 
https://www.loom.com/share/a3ebc6df72ff4f05af0d36df1b0fb244

**Comment by vadymboichenkoAcupower** [comment]
Зрозумів. Я деякі зміни забув запушити. Добре. Дороблю і відправлю. Дякую за відео

**Review by Viktor-Kost — CHANGES_REQUESTED** [review]
Hello!)
Nice work

### To improve:
1. Add cursor: pointer to links and buttons
2. Add favicon
3. Display phone number when you hover at phone icon
4. Increase all images on hover (make them links to #, if there is no better option)
5. Remove page scrolling when menu is opened
6. Form inputs should be required
7. You should be able to submit a form
8. There are links, not just text
Screenshot 2023-07-03 at 21 18 54

9. Logo size doesn't math the design
Screenshot 2023-07-03 at 21 17 02

**Review by nazarmatsevych — CHANGES_REQUESTED** [review]
Hey, looks like you didn't push anything since last review. Please push your changes and then re-request review.

If you have any questions - feel free to ask them in fe_chat

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work! Added comments to fix: 
Screenshot 2023-07-04 at 14 55 13
Font sizes don't match the Figma design
Screenshot 2023-07-04 at 14 53 02
The image for the tablet doesn't match the Figma design
Screenshot 2023-07-04 at 14 52 22
Screenshot 2023-07-04 at 14 49 02
I can see the burger menu after clicking and it breaks a layout
Screenshot 2023-07-04 at 14 51 54
The footer image position doesn't match the Figma design for desktop
Screenshot 2023-07-04 at 14 51 38
Check the font size for the contacts block. 
Screenshot 2023-07-04 at 14 50 47
Screenshot 2023-07-04 at 14 50 57
Screenshot 2023-07-04 at 14 51 05 Sections overlaps on hover. Consider fixing it and avoiding such behavior

**Pull request closed without merging**
