### PR TITLE
header and menu

### PR DESCRIPTION
**Pull request by IrynaVlasenko**
https://IrynaVlasenko.github.io/layout_landing-page/

### CODE REVIEW

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Good start 👍 
Let's improve your page
1. You need to check indents left and right
Demo
image

Design
image

2. Title on demo
image

Design
image

3. Menu on demo
image

Design
image

**Comment by IrynaVlasenko** [comment]
Thanks for review!
 I had started from demo of mobile version (320px) and about indents left and right it's not like in 1260px

**Review by loralevitska — CHANGES_REQUESTED** [review]
Keep up the good work! Some comments to fix:
- add right page paddings for desktop mode 
image
image
- add phone number by phone icon hover
image
- phone icon should be link with href="tel: ...."
image
- disable scroll while menu is open 
image
- re-request next review after completing all blocks

**Comment by IrynaVlasenko** [comment]
> https://IrynaVlasenko.github.io/layout_landing-page/

Please see mobile version

**Pull request closed without merging**
