### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ikispower**
[DEMO LINK](https://ikispower.github.io/layout_landing-page/)

### CODE REVIEW

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Good start 👍 
Let's improve your page
1. Need to remove scroll when this menu is open
image

2. Add `cursor: pointer` for all clickable elements
image

3. Need to change autocomplete styles for inputs
image

4. Make all these fields are required before clicking send
image

**Review by loralevitska — CHANGES_REQUESTED** [review]
You did an amazing job! Looks good! Let's do some improvements (check comments)

- make this phone number reachable 
image
- add anchor to this 
image
- implement this requirement from checklist 
image
- don't show this number on mobile mode 
image

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Demo link, you need to make a deploy
image

**Comment by ikispower** [comment]
can't deploy

**Review by mykhalenych — CHANGES_REQUESTED** [review]
your demo link isn't working, if you have questions add them to chat

**Pull request closed without merging**
