### PR TITLE
landing page - b&o

### PR DESCRIPTION
**Pull request by moskalenkosergii**
[DEMO LINK](https://moskalenkosergii.github.io/layout_landing-page/)

[LAYOUT](https://www.figma.com/file/DtkQmQ797hk0nI4KfMi2Uq/BOSE-New-Version?node-id=6817%3A271&mode=dev)

### CODE REVIEW

**Review by anastasiia-tilikina — CHANGES_REQUESTED** [review]
This is great project 🔥 

Very well done!
I love your minimalistic hover effects on images)

The only one suggestion:
image

1. make all fields required.
2. disable resize for textarea + fix font styles for it

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
1. Still not fixed from the previous review
Users will not be able to change the size of this field
image

2. Make all these fields are required before sending
image

3. Need to check the styles for phone number text as on the design
image

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Make sure to deploy your page

**Review by anastasiia-tilikina — CHANGES_REQUESTED** [review]
I see changes in your code but nothing is change on your demo(

did you redeploy your project?

**Comment by moskalenkosergii** [comment]
Yes, I did. But I think this build has problems with deploy. I don't know how to fix it, the team at MA didn't help.

**Review by etojeDenys — CHANGES_REQUESTED** [review]
please, feel free to ask for help with deploy in the chat

**Pull request closed without merging**
