### PR TITLE
add task solution

### PR DESCRIPTION
**Pull request by Ivakhovd**
[DEMO LINK](https://Ivakhovd.github.io/layout_landing-page/)

### CODE REVIEW

**Comment by TarasHoliuk** [comment]
1. Check font color here:

Design:
image

App:
image

2. Export the image without red lines at the bottom and top of the image:
image

3. Export SVG images for logo and icons. It will provide better-quality images:
image

Figma:
image

**Review by TarasHoliuk — CHANGES_REQUESTED** [review]
GJ 👍 

Let's improve a few things in this stage - read comments

**Comment by Ivakhovd** [comment]
Bug fixed

**Review by etojeDenys — CHANGES_REQUESTED** [review]
good job, keep going, you'll finish this task in the next sections

**Comment by Ivakhovd** [comment]
@etojeDenys what's wrong with my code? How can I correct mistakes?

**Pull request closed without merging**
