### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by viktor-kniahnytskyi**
- [DEMO LINK](https://viktor-kniahnytskyi.github.io/layout_landing-page/)

### CODE REVIEW

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
Good start.
Finish header section and waiting other sections.

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
Good job.
Needs some improvements
- prevent scrolling page when menu open ( 11 point from [checklist](https://github.com/mate-academy/layout_landing-page/blob/main/checklist.md))
- Change text color on hover for phone, email and address.
- on hover phone icon should appear phone number tooltip
Screenshot from 2023-07-30 18-11-49
- add cursor pointer for send button. check other interactive elements.
- consider to make custom scrollbar for textarea
   https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp
- fix default autocomplete styles for inputs
   https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/
  
Screenshot from 2023-07-30 18-07-57

**Review by Viktor-Kost — CHANGES_REQUESTED** [review]
Hello!
Nice work!

### To improve: 
1) add hover effect to the `contact us` section links

**Review by IvanFesenko — CHANGES_REQUESTED** [review]
Well done

**Review by IvanFesenko — APPROVED** [review]

**Pull request closed without merging**
