### PR TITLE
My Bike landing

### PR DESCRIPTION
**Pull request by Arthur-Tolkachov**
## Description
Created new landing

[DEMO_LINK](https://arthur-tolkachov.github.io/layout_landing-page/)

### CODE REVIEW

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
Try to run `npm run deploy` again 
image

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work! Consider exporting an image without the label 
Screenshot 2024-06-06 at 13 51 21
Also, consider removing the default outlines 
Screenshot 2024-06-06 at 13 51 32
A user should be able to call by clicking here 
Screenshot 2024-06-06 at 13 51 11

**Comment by Arthur-Tolkachov** [comment]
@anastasiiavorobiova is it a good idea to remove outlines from the inputs? Anyway, I've all done.

**Review by anastasiiavorobiova — APPROVED** [review]
Awesome work!

**Pull request closed without merging**
