### PR TITLE
first landing))

### PR DESCRIPTION
**Pull request by OleksandrFEdev**
- Deploy and create a Pull Request with a [DEMO LINK](https://OleksandrFEdev.github.io/layout_landing-page/)

### CODE REVIEW

**Review by nazarmatsevych — CHANGES_REQUESTED** [review]
Great work, here are some improvements:

1. Use phone link like in example below for all phone numbers
image


2. Add hover effects for images, for example scale
image

image

3. I have this screen after form submit, but form should not reload on submit and also you have to clear form fields on button click
image
image

4. This link should lead to real address in google maps
image

5. Add paddings to you page bottom like in design

image

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
1. When I click here nothing happens
image

2. Need to remove scroll when this menu is open
image

3. Need to change default styles for input after autocomplete
image

**Review by IvanFesenko — CHANGES_REQUESTED** [review]
Click on adress link should open new tab, add target="_blank"
2023-07-28_14h37_19

Onwide screens hovered images overlapping each other
2023-07-28_14h38_12
2023-07-28_14h38_18

Something were wrong on resolution ~1040px
2023-07-28_14h40_16

There are horizontal scroll
https://github.com/mate-academy/layout_landing-page/assets/61904995/a672b2ed-f442-4829-a42c-966952ab7a35

**Review by VitaliyBondarenko1982 — APPROVED** [review]
Well done!

**Comment by OleksandrFEdev** [comment]
Thanks, mr.Vitaliy🤝

**Comment by OleksandrFEdev** [comment]
> Well done!

Thanks, mr.Vitaliy🤝

**Pull request closed without merging**
