### PR TITLE
21landing-page

### PR DESCRIPTION
**Pull request by timohahaaa**
https://timohahaaa.github.io/layout_landing-page/

### CODE REVIEW

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
Good job.
Needs some improvements.
Please proofread [checklist](https://github.com/mate-academy/layout_landing-page/blob/main/checklist.md)
- disable scroll when menu is open. increase z-index for menu
Screenshot from 2023-10-01 16-28-08
- all images should increase on hover
- add transition for all elements with hover effect
- prevent such behavior for textarea
chrome-capture-2023-9-1 (2)
- contact us section doesn't much to design for desktop. 
design:
design-contacts
actual:
actual-contacts

- for mobile form should be on full width of screen
Screenshot from 2023-10-01 16-30-47
- add hover (change color) for email, phone, address. google map should open in new tab, email also should be a link and open window for writing email
Screenshot from 2023-10-01 16-34-31
- fix autocomplete styles for inputs
https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/
Screenshot from 2023-10-01 16-34-08
- suggest to make custom scrollbar
https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp
Screenshot from 2023-10-01 16-33-54

**Review by maxim2310 — CHANGES_REQUESTED** [review]
1. need to remove scroll while menu open
2. when hover on phone you must to show a phone number like in design
3. add scale on hover  
image
4. add cursor pointer
image
5. fix input field and make right part like design 
image
6. and check previous comments

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
1. Add a transition for hover effects here
image

2. Need to remove scroll when this menu is open
image

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
1. Need to make all these fields are required before send
image

2. Need to fix the background image on the tabler version
Demo
image

Design
image

**Comment by TarasHoliuk** [comment]
1. Transition works only in one way (decrease happens immediately):

[Screencast from 15-10-23 10:17:14.webm](https://github.com/mate-academy/layout_landing-page/assets/86923089/081c7de9-f5d3-4960-94a0-00b8896f81bf)

To fix it set a transition for element, not for `element:hover`:
Screenshot from 2023-10-15 10-18-49

2. Import it without a label (left-bottom corner):
image

**Review by TarasHoliuk — CHANGES_REQUESTED** [review]
Well done :+1:  Nice scroll bar :fire: 
Let's fix 2 more things

**Review by anastasiiavorobiova — APPROVED** [review]
Awesome work!

**Pull request closed without merging**
