### PR TITLE
add landing page

### PR DESCRIPTION
**Pull request by teejrs**
[DEMO LINK](https://teejrs.github.io/layout_landing-page/)

### CODE REVIEW

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Good job 👍 
Let's improve your code
1. Make all these fields are required before sending
image

2. Need to remove the autocomplete styles

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Now you just deleted the autocomplete, this is not the right solution, you just need to stylize this autocomplete, so you need to return it and stylize, you can read how to do it here
https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/
image

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
1. Need to fix the image width here as on the design
image

2. Add a transition when this menu appears on the page
image

3. Need to hide these phone number on the tablet and mobile versions
image

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
You have a great progress here! Will be waiting for implementing a responsive page
Screenshot 2023-10-24 at 15 24 10
Consider fixing the validation error
Screenshot 2023-10-24 at 15 24 24
A user should be able to pick a phone number and call
Screenshot 2023-10-24 at 15 26 24

Screenshot 2023-10-24 at 15 26 04
Check a container width
Screenshot 2023-10-24 at 15 25 47
Check indents here
Screenshot 2023-10-24 at 15 26 40
Consider reducing the element width on hover to avoid overlapping.

**Pull request closed without merging**
