### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ApheliosGM**
[DEMO LINK](https://ApheliosGM.github.io/layout_landing-page/)

### CODE REVIEW

**Review by denys-danyliuk — CHANGES_REQUESTED** [review]
it seems to me that you forgot to go through checklist before sending landing on a review, you should always do it before requesting a review

https://github.com/mate-academy/layout_landing-page/blob/main/checklist.md

**Review by denys-danyliuk — CHANGES_REQUESTED** [review]
6'th point in checklist
Знімок екрана 2023-10-12 о 09 58 53
 
you can increase whole block on hover, not only image
Знімок екрана 2023-10-12 о 09 59 26

nav__links doesn't work, they should lead to particular sections, also add transition to them
Знімок екрана 2023-10-12 о 10 00 31

this button should also start a call
Знімок екрана 2023-10-12 о 10 00 55

11'th point in checklist
Знімок екрана 2023-10-12 о 10 01 32

add background to navbar to avoid this when menu is higher than viewport
Знімок екрана 2023-10-12 о 10 01 57

this doesn't look like real phone number
Знімок екрана 2023-10-12 о 10 02 36

I can't send the form, also all fields should be required and have validation
Знімок екрана 2023-10-12 о 10 03 20

16'th point in checklist

**Review by denys-danyliuk — CHANGES_REQUESTED** [review]
this link should start a call
Знімок екрана 2023-10-16 о 17 11 40

this link doesn't work, also add transition to make the appearance of line smooth
Знімок екрана 2023-10-16 о 17 11 43

delete paddings for menu__top element because now it looks bad
Знімок екрана 2023-10-16 о 17 13 41

you should wrap these fields in form because now they doesn't work as they supposed to
Знімок екрана 2023-10-16 о 17 14 55

pay attention to the 16'th point in checklist

**Review by etojeDenys — CHANGES_REQUESTED** [review]
1. looks different
image
image


2. make all fields in form required

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
1. Need to remove autocomplete styles. Also when I click send nothing happens
image

2. Need to fix the indents between these elements as on the design
image

**Review by IvanFesenko — CHANGES_REQUESTED** [review]
Good job. Found some issues:
- Fix this image export, no additional items should be on it
2023-10-30_16h03_14

-Form should reset on after submit
- Images overlapping menu. To fix incease z-index for menu
https://github.com/mate-academy/layout_landing-page/assets/61904995/bb6f8e47-5f8f-49ae-a011-170d788f6aa0

**Pull request closed without merging**
