### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by pasha30061**
[DEMO LINK](https://pasha30061.github.io/layout_landing-page/)

### CODE REVIEW

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great start! Consider fixing validation errors 
Screenshot 2023-10-07 at 09 18 17
Add hovers for interactive elements 
Screenshot 2023-10-07 at 09 17 41
Screenshot 2023-10-07 at 09 17 26
A user should be able to see the phone number on the hover

**Comment by pasha30061** [comment]
[DEMO LINK](https://pasha30061.github.io/layout_landing-page/)
Aded:
- favicon
- hover efects for nav__links and icons
- delete spaces in href

**Review by Andriy-Shymkiv — CHANGES_REQUESTED** [review]
- use svg instead of png:
image

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Good start 👍 
1. Add the indents on the left and right
image

2. Add transition when this menu appears on the page
image

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Still not fixed from the previous review

**Review by etojeDenys — CHANGES_REQUESTED** [review]
good job, keep going

**Review by xiimiik — CHANGES_REQUESTED** [review]
Nice! Waiting for the full landing page after completing the all modules)

**Review by xiimiik — CHANGES_REQUESTED** [review]
strange gray box on header
image

phone number should be centered
image

i cant close menu on second menu button click
image

footer is broken
image

inputs are jumping on hover
image

remove outline on focus
image

add transition for animations
image

images are overlaping on hover
image
image

add cursor pointer
image

too many of free space at the bottom
image

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
The work looks really nice! 
Screenshot 2023-10-25 at 14 20 57
Check the background position for the tablets
Screenshot 2023-10-25 at 14 20 27
The navigation overlaps the logo on scroll in landscape mode
Screenshot 2023-10-25 at 14 20 08
Consider removing outlines from form fields
Screenshot 2023-10-25 at 14 19 43
Check font sizes here
Screenshot 2023-10-25 at 14 18 53
Consider centering your container

**Review by DarkMistyRoom — APPROVED** [review]
only one suggestion: add a bottom indent to the menu to make it look fine in the landscape mode
image

**Pull request closed without merging**
