### PR TITLE
Bang&Olufsen landing

### PR DESCRIPTION
**Pull request by maksym-kostetskyi**
demo link: https://maksym-kostetskyi.github.io/layout_landing-page/#

### CODE REVIEW

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
1. Get rid of horizontal scroll 
image
2. Restrict textarea resize
image
3. Make the transition the same for the entire page

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
Make sure that you run npm run deploy after make changes 
1. Vertical scroll still exist 
image
2. 
image

**Review by etojeDenys — CHANGES_REQUESTED** [review]
1. it does not should to overlap text
image
2. fix this mismatch
image
image
3. add some transition to everything
4. number must appear on hover
image

**Review by loralevitska — CHANGES_REQUESTED** [review]
Almost perfect) Let's improve

- pay attention to the details, you need to make it so that this number can be clicked and it is a link, if necessary, rewatch the landing guide
image
- add cursor pointer to each clickable elements
- would be great if something happen by click on this button. You can find their original site and link there
image
- add hover effect to this links 
image
- remove default autocomplete background-color, it breaks design
image

**Review by DarkMistyRoom — CHANGES_REQUESTED** [review]
Few small fixes:
- make the menu appear smoothly
- and smooth hover effect for buttons and these links
image

- check the contact section on the tab. It looks different in the mockup

- add bottom indent to the menu content
image

**Review by etojeDenys — APPROVED** [review]
lgtm

**Pull request closed without merging**
