### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by BohdanKapko**
[DEMO LINK](https://BohdanKapko.github.io/layout_landing-page/)

### CODE REVIEW

**Review by IvanFesenko — CHANGES_REQUESTED** [review]
Good start, kepp going. Do not forget:
- Add favIcon
- Check design
Actual result: 
2024-02-13_10h06_25
Expected result:
2024-02-13_10h06_30

**Comment by BohdanKapko** [comment]
this task concerns only the mobile part if I'm not mistaken

**Review by IvanFesenko — CHANGES_REQUESTED** [review]
This is long way task. Approve will be only after full landing implementation. If you have any questions - ask them in fe_chat

**Review by IvanFesenko — CHANGES_REQUESTED** [review]
Good job, list of issues:
- add favIcon
- horizontal scroll on all resolutions
- Add hover effects to images (scale for example)
- remove autocomplete styles (blue background), form should have all fileds required, form submit should nor reload page (just clear form)
2024-03-21_15h29_13
- should be links with hover effects as well
2024-03-21_15h30_29
- fix this case
2024-03-21_15h31_47

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work! 
Screenshot 2024-03-25 at 14 04 22
Check the font here 
Screenshot 2024-03-25 at 14 04 00
Please, add a proper href attribute here 
Screenshot 2024-03-25 at 14 03 49
Consider adding a cursor pointer to the button hover 
Screenshot 2024-03-25 at 14 03 23
A user should be able to call by clicking here

**Pull request closed without merging**
