### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by BohdanDymydiuk**
[DEMO LINK](https://BohdanDymydiuk.github.io/layout_landing-page/)

### CODE REVIEW

**Review by nazarmatsevych — CHANGES_REQUESTED** [review]
Great work but i can't click on numbers

**Comment by BohdanDymydiuk** [comment]
I cant's see your image.

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
1. This image for the previous review, still not fixed
image

2. Add cursor pointer for buttons
image

3. You need to center these elements on the page horizontally
image

4. These elements should be width 100% 
image

**Review by loralevitska — APPROVED** [review]
Good job!
Check menu paddings, would be better to make cross icon and burger menu icon on page at the same position 
image

**Pull request closed without merging**
