### PR TITLE
solution

### PR DESCRIPTION
**Pull request by Yehorf21**
[DEMO LINK](https://Yehorf21.github.io/layout_landing-page/)

### CODE REVIEW

**Comment by Yehorf21** [comment]
I had to delete my previous repository and create a new one because of some problems with Demo Link

**Review by etojeDenys — CHANGES_REQUESTED** [review]
.

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
1. form submit should reset form
2. all external links should be open in the separate tab

**Comment by Yehorf21** [comment]
Everything got fixed

**Pull request closed without merging**
