### PR TITLE
Add the basic page implementation

### PR DESCRIPTION
**Pull request by GoVolodya**
- Deploy and create a Pull Request with a [DEMO LINK](https://GoVolodya.github.io/layout_landing-page/)

### CODE REVIEW

**Comment by TarasHoliuk** [comment]
1. The font on the entire page is wrong (and the title shouldn't be in upper case):

image

Design:

image

**Review by TarasHoliuk — CHANGES_REQUESTED** [review]
Hey! You did a great job. There are some things that should be improved (read comments). Also, read the [checklist](https://github.com/mate-academy/layout_landing-page/blob/main/checklist.md) to make sure you've reached all points

**Comment by GoVolodya** [comment]
Sure, I forgot about check list. Please check the changes, as now it should look much more better.

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Make sure to deploy the page 
Screenshot 2024-05-26 at 16 20 43

**Comment by GoVolodya** [comment]
I did run the 'npm run deploy' but for some reason styles are missing. Guess I have to figure it out by myself.

Screenshot 2024-05-26 at 16 31 08

**Pull request closed without merging**
