### PR TITLE
added mobile main page & menu

### PR DESCRIPTION
**Pull request by AlNeon**
[DEMO LINK](https://AlNeon.github.io/layout_landing-page/)

### CODE REVIEW

**Review by etojeDenys — CHANGES_REQUESTED** [review]
1. number should appear on hover
image


2. let's import the icons as svg images, it will approve the quality of at least
image

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great start! 
Screenshot 2023-10-07 at 09 44 57
Check the text size here
Screenshot 2023-10-07 at 09 43 38
Screenshot 2023-10-07 at 09 44 14
Check icon sizes
Screenshot 2023-10-07 at 09 43 14
Screenshot 2023-10-07 at 09 43 23
Check the size of the logo
Screenshot 2023-10-07 at 09 42 33
Consider adding hovers for all interactive elements
Screenshot 2023-10-07 at 09 42 12
Screenshot 2023-10-07 at 09 42 19
The phone number should be shown on the hover

**Review by etojeDenys — CHANGES_REQUESTED** [review]
still not fixed
image

**Review by etojeDenys — APPROVED** [review]
good job, keep going

**Pull request closed without merging**
