### PR TITLE
add task solution

### PR DESCRIPTION
**Pull request by MaksymKos**
https://maksymkos.github.io/layout_landing-page/

### CODE REVIEW

**Review by Viktor-Kost — CHANGES_REQUESTED** [review]
Hello!)
Nice work!

**To improve:** 
- Logo should be as svg
- Remove default blue outline for inputs
- No needs to require such a big amount for characters at textarea
- Page shouldn't be reloaded on form submit
- Decrease transition-duration. Usually we use 250-300 ms
- Disable page scrolling under the menu
- Fix box-shadow at hover 
Screenshot 2023-06-08 at 19 59 53

**Highly recommended**
As an example, let's take your header background
- Use different images for different screen sizes (mobile, tablet, desktop) using media-queries. We don't want to use big image file size from desktop for mobile. It's ruining your website experience. [Here](https://www.theessential.agency/blog/are-images-ruining-your-website-experience) you can find why is it important
- Use optimized images. [Here](https://squoosh.app/) is an app that can help you to compress your images. Imagine that user have 3g connection and open your website with a phone. 6mb is too big to download

**Comment by MaksymKos** [comment]
Done without "Fix box-shadow at hover"

**Review by OleziO — CHANGES_REQUESTED** [review]
Demo: 
image
Design: 
image

Demo: 
image
Design: 
image

Check other similar cases

==================

Demo: 
image
Design:
image

**Review by anastasiia-tilikina — CHANGES_REQUESTED** [review]
Please, look carefully on previous comments and make sure that you've fixed all the issues before re-requesting review)
If you have any questions fell free to ask them in slack chat🙌

**Pull request closed without merging**
