### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by AnastasiiaKriuchkova**
[DEMO LINK](https://<AnastasiiaKriuchkova>.github.io/layout_landing-page/)

### CODE REVIEW

**Review by mykhalenych — CHANGES_REQUESTED** [review]
your demo link isn't working

**Comment by AnastasiiaKriuchkova** [comment]
> your demo link isn't working

[DEMO LINK](https://<AnastasiiaKriuchkova>.github.io/layout_landing-page/)

**Comment by AnastasiiaKriuchkova** [comment]
[> DEMO LINK
](https://anastasiiakriuchkova.github.io/layout_landing-page/)

**Review by mykhalenych — CHANGES_REQUESTED** [review]
1. add hover on phone icon and show phone number
2. check design all your blocks are different
Screenshot 2023-05-31 at 16 22 42
Screenshot 2023-05-31 at 16 22 53
Screenshot 2023-05-31 at 16 23 01
Screenshot 2023-05-31 at 16 23 11
Screenshot 2023-05-31 at 16 23 23

**Pull request closed without merging**
