### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by troleksii**
DEMO LINK - https://troleksii.github.io/layout_landing-page/

### CODE REVIEW

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Good job 👍 
Let's improve your page
1. Add a favicon on the page
image

2. Need to make a call when clicking on this icon
image

3. Add transition when this menu appears on the page
image

4. Add hover effects for all clickable elements on the page
image

5. Add hover effects for images
image

6. Add cursor pointer for buttons
image

7. Need to change the autocomplete styles for the inputs
image

8. Add hover effects here
image

**Review by l4st1m0za — CHANGES_REQUESTED** [review]
Good job, but some places can be improved: 

1) This is good idea for the icon hover, but I think that it's better to just increase the icon on the hover
image

2) All the animation should be smooth

3) Photos of bikes should be in the center of their block 
image

4) Make fields required
image

5) Menu and header elements should be placed on the same places. When I open menu, it's elements are not on the same spot

**Review by maxim2310 — CHANGES_REQUESTED** [review]
Good work, but lets make some improvement 

1. it must looks according design and number must be reachable 
image
image
2. on tablet need to check main img position 
image
image
3. same on mobile
4. check indent here
image

**Review by etojeDenys — APPROVED** [review]
lgtm

**Pull request closed without merging**
